### ISSUE TITLE
Fix the view of the navbar 

### ISSUE THREAD

**Issue by ChrisS561** [ChrisS561/author-books-website#26]
Fix the navbar to the elevated navbar : https://mui.com/material-ui/react-app-bar/#elevate-app-bar

**Comment by Sky-De** [comment]
@ChrisS561 assign this to me
I would like to fix this
Thanks

**Comment by ChrisS561** [comment]
I've assigned this task to you. Thank you for volunteering to fix it! Please go ahead and make the necessary changes, and feel free to reach out if you have any questions or need further assistance.

Thanks for your help!

**Comment by Sky-De** [comment]
@ChrisS561 Hi again, I fixed the issue but there was some issue
with the elevated navbar there were problems with the contrast so I've used the Hide App bar instead, it looks much better and also provides better UX, I will attach gif of result

**GIF**
![chrome-capture-2023-9-1-min](https://github.com/ChrisS561/author-books-website/assets/79264045/32f3d158-fe71-4641-8d24-8c731f026802)


If you got any question feel free to ask, otherwise let me know to create PR of solution for this issue 
thanks

**Comment by ChrisS561** [comment]
@Sky-De That was one of my main concerns when it came to implementing the elevated navbar, but yes, I agree; I believe that the Hide App bar looks better as well. Feel free to make a pull request!
